import jsPDF from "jspdf";

const SCHOOL_NAME = "Tadika Khalifah Muda";

function formatMoney(n) {
  const num = Number(n);
  if (Number.isNaN(num)) return "0.00";
  return num.toLocaleString("en-MY", { minimumFractionDigits: 2, maximumFractionDigits: 2 });
}

function formatDate(d) {
  if (!d) return "—";
  try {
    return new Date(d).toLocaleString("en-MY", {
      dateStyle: "medium",
      timeStyle: "short",
    });
  } catch {
    return String(d);
  }
}

/**
 * Builds a fee payment receipt PDF and triggers browser download.
 * @param {Object} opts
 * @param {string} [opts.schoolName]
 * @param {string} opts.payerName
 * @param {string} opts.studentName
 * @param {Object} opts.invoice — amount, category, status, _id
 * @param {Array<Object>} opts.payments — amountPaid, method, paidAt, note
 */
export function downloadFeeReceiptPdf({
  schoolName = SCHOOL_NAME,
  payerName,
  studentName,
  invoice,
  payments,
}) {
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  const pageW = doc.internal.pageSize.getWidth();
  const margin = 18;
  let y = 22;

  const invId = String(invoice._id || "");
  const receiptNo = invId ? `INV-${invId.slice(-8).toUpperCase()}` : `RCP-${Date.now()}`;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(16);
  doc.text(schoolName, pageW / 2, y, { align: "center" });
  y += 8;

  doc.setFontSize(12);
  doc.text("FEE PAYMENT RECEIPT", pageW / 2, y, { align: "center" });
  y += 12;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setDrawColor(200);
  doc.line(margin, y, pageW - margin, y);
  y += 8;

  const row = (label, value) => {
    doc.setFont("helvetica", "bold");
    doc.text(label, margin, y);
    doc.setFont("helvetica", "normal");
    const lines = doc.splitTextToSize(String(value ?? "—"), pageW - margin * 2 - 45);
    doc.text(lines, margin + 42, y);
    y += Math.max(6, lines.length * 5);
  };

  row("Receipt ref:", receiptNo);
  row("Issued:", formatDate(new Date()));
  row("Received from:", payerName || "Parent / Guardian");
  row("Student:", studentName || "—");
  row("Fee category:", invoice.category || "—");
  row("Invoice total (RM):", formatMoney(invoice.amount));
  row("Invoice status:", (invoice.status || "—").toUpperCase());

  y += 4;
  doc.setFont("helvetica", "bold");
  doc.text("Payment records (this invoice)", margin, y);
  y += 7;

  doc.setDrawColor(220);
  doc.line(margin, y, pageW - margin, y);
  y += 6;

  doc.setFontSize(9);
  const sorted = [...(payments || [])].sort(
    (a, b) => new Date(a.paidAt || 0) - new Date(b.paidAt || 0)
  );

  let totalPaid = 0;
  sorted.forEach((p, i) => {
    totalPaid += Number(p.amountPaid) || 0;
    doc.setFont("helvetica", "bold");
    doc.text(`#${i + 1}`, margin, y);
    doc.setFont("helvetica", "normal");
    doc.text(`${formatDate(p.paidAt)}  ·  ${p.method || "—"}`, margin + 12, y);
    y += 5;
    doc.text(`RM ${formatMoney(p.amountPaid)}${p.note ? `  ·  ${p.note}` : ""}`, margin + 12, y);
    y += 8;
    if (y > 270) {
      doc.addPage();
      y = 20;
    }
  });

  if (sorted.length === 0) {
    doc.setFont("helvetica", "italic");
    doc.text("No payment lines.", margin, y);
    y += 8;
  }

  doc.setFont("helvetica", "bold");
  doc.text(`Total paid (this invoice): RM ${formatMoney(totalPaid)}`, margin, y);
  y += 10;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.setTextColor(100);
  doc.text(
    "This document was generated by KMMS for your records. Please retain for your files.",
    margin,
    y
  );

  const safeFile = `KMMS-Receipt-${receiptNo.replace(/[^a-zA-Z0-9-_]/g, "")}.pdf`;
  doc.save(safeFile);
}
